### ISSUE TITLE
Quest Suggestion/Feedback

### ISSUE THREAD

**Issue by DrasticDemise** [DrasticDemiseFTBPacks/Banished#35]
List any quests that are not clarified enough, or suggest new quests below.

**Comment by Mechalith** [comment]
Possibly a quest section for Dark Power generation in specific? A 24 hour cycling repeatable quest is a bit frustrating when a lot of the initial tools you need are behind a power-wall that is going to take 4-5 game days to reach.  (My view on this might be skewed because I've only been able to get zombies to spawn, so I have to kill 3 and then run away until the quest recharges, repeat as needed.)

It would also be nice if the sapling quest weren't dependent on the seed quest, esp since there's also a quest in the Survival branch that also gives you a seed. Having to burn power and time on a redundant wheat seed is irritating.

**Comment by DrasticDemise** [comment]
I plan on going back and adding early game reputation rewards on the quest lines, and now that you can't skip time I will probably lower the cool down to 12 hours, which is 10 minutes minecraft time.

**Comment by Mechalith** [comment]
Two minium dust as a quest reward for the alchemical chests is a bit low IMO. You've got to burn through something like 12 minium dust worth of materials to make them in the first place.

**Comment by Mechalith** [comment]
For the survival quest that has you make an iron sword, you might consider switching it to a consume task and make the reward a soulbound iron sword instead of the stone one. That way it feels a bit more like you're building better equipment instead of making a nicer sword and then being given a slightly more convenient but less effective one.

**Comment by DrasticDemise** [comment]
Alright, both noted. Thanks

**Comment by ConfigsPlease** [comment]
A number of quests in the Dark Power section seem to not be reputation-locked properly - I was able to complete them all (still lowering my reputation) without having the full amount required - this put me at -36. Off the top of my head: Magelight, AOE Dig, Mining Beam, Magnetism all suffered from this.

**Comment by DrasticDemise** [comment]
Huh, I can't reproduce that. Did you have multiple soul bound player foci?

**Comment by ConfigsPlease** [comment]
I did not. Odd that it can't be reproduced..

**Comment by DrasticDemise** [comment]
It isn't that big of a deal since it  stops them from getting any other items until they bring their reputation all the way back up, but ¯\_(ツ)_/¯

**Comment by Mechalith** [comment]
(moved to separate Aura Cascade thread)
