### ISSUE TITLE
Aura Cascade Crystals - Crafting

### ISSUE THREAD

**Issue by ConfigsPlease** [DrasticDemiseFTBPacks/Banished#48]
One of the quests under Dark Power (which rewards the player with Aura Cascade white crystals) says that the aura cannot be made or destroyed. I just find it odd that the crafting recipes for the crystals are still enabled - A diamond surrounded by 8 glass to produce 16(?) crystals, and/or a mana ingot surrounded by panes to produce 4. Just double-checking if this is intentional - I'm not very familiar with the mod as a whole, so I don't know how many of the things you need / if the mod can produce them itself outside of regular crafting.

**Comment by Mechalith** [comment]
The whole 'cannot be created or destroyed' deal is from the mod itself, but it actually says 'usually'. When you make an aura crystal you aren't creating aura, you're just focusing some into a portable concentrated form. It's mainly in there (as far as I know) because the mod dev wanted to emphasize that you're not generating magical energy, just taking advantage of the effects it causes when moved around.

**Comment by ConfigsPlease** [comment]
Interesting, must've read it wrong. Oh well.
