### ISSUE TITLE
Broken Quests

### ISSUE THREAD

**Issue by DrasticDemise** [DrasticDemiseFTBPacks/Banished#67]
Submit and quests that are non-functional here.

**Comment by Mechalith** [comment]
Did some checking in edit mode and in ver. 1.0.1, it looks like the rep requirements for a bunch of the dark power quests have been removed, which would explain why people are able to plow their way into the negatives.

Edit: scratch that, I'm just reading it wrong.

**Comment by DrasticDemise** [comment]
I was considering adding in another reputation check before they attempt to start the focus process so they don't get trapped into a high rep quest if they didn't read the reward first.

**Comment by Mechalith** [comment]
The only trouble there is that I think the initial rep check will go off as soon as they reach that rep level, and I'm not sure it'll DQ them if it drops.

If I could suggest a separate option? Add Quadrum (or do this with Accidentally Circumstantial) and add an item made of crystalized Dark Power to use as currency. That would eliminate the need to fidget around with the flaky as hell HQM rep system entirely.

EE3 can be set to disallow learning something as a transmutation, so that isn't a concern, and thematically I think it'd work well with the focus on Aura Cascade.

'In this strange place, the dark power I gather from the lives of my enemies seems to concentrate down into these odd gems instead of entering me directly as mana normally would. No matter. I can carry them easily enough, until I have need of the energy within.'

**Comment by Mechalith** [comment]
For that matter, using a 'black fragment' type of item would also eliminate the need for the dark power generation _quests_, so you wouldn't need to juggle which creatures were worth giving a quest slot to. (and people wouldn't have to manually hand them in mid-slaughter, which I'm sure they'll be happy about.)

**Comment by joakibj** [comment]
The Golemancy quest seems to have an Invalid item as reward.

http://i.imgur.com/SqPtSTv.png

I manually added these mods:
Aroma1997Core-1.7.10-1.0.2.13.jar
AromaBackup-1.7.10-0.0.0.5.jar
extrautilities-1.2.5.jar (only enabled builder's wand)
MouseTweaks-2.4.4-mc1.7.10.jar
tcnodetracker-1.7.10-1.1.1.jar

**Comment by DrasticDemise** [comment]
SO THAT IS WHAT BROKE THE HUBRIS QUEST DATA. Will look into it, thanks.

**Comment by joakibj** [comment]
How is the dungeon caller supposed to work? I threw it on the ground, said it spawned a dungeon at x,z coords. I dug down to y=1, nothing. Dug a stairwell up to y=254 and then dug down from there on the x,z coords. Didn't find any dungeon

**Comment by Mechalith** [comment]
Joakibj: That's pretty much exactly how it's supposed to work, but it should have spawned something. You may need to widen your search a bit, when I used mine it actually spawned a bit off to one side, and since they can be odd shapes and have the occasional gap it is possible to miss them.

All the caller does is trigger the Doomlike Dungeon's "make a dungeon right here" script though, so it's mostly a quirk of the mod and not the caller item in specific.

**Comment by joakibj** [comment]
I reckon I should have found the thing after digging a stairwell along the border of the chunk, or at least triggered spawners and being able to see them on the journeymap, though.

**Comment by Mechalith** [comment]
Probably, yeah. Where were you when you spawned the dungeon?

**Comment by joakibj** [comment]
Y-level 40 something and threw the thing on the ground. It's not a big deal, I just wanted some spawners to get zombie brains. With zombies being exceedingly rare to find

**Comment by Mechalith** [comment]
It may not be the end of the world, but it'd still be nice to fix if possible. If you cheat in another caller, does it do the same thing?

**Comment by DrasticDemise** [comment]
It should have spawned at the coords it gave you, if there is nothing there it may have ate the dungeon.

If that is the case, there isn't anything I can do since the item simply executes the command from the mod, no special cheaty command by me
