### ISSUE TITLE
Have a problem with the server files?

### ISSUE THREAD

**Issue by DrasticDemise** [DrasticDemiseFTBPacks/Banished#91]
1. Accept the EULA.
2. Make sure the following mods are not in the server instance: Dynamic Lighting, Launch GUI, LockDown, JourneyMap, Resource Loader.

All other issues may be posted below.

**Comment by Dragonic-magic** [comment]
Im having troubles with the batch file as i run it i come up with the problem of missing libraries, tho im not entirely the best at servers ive never come across a server i couldnt run due to libraries at least without the server fixing itself with a library install file like in the direwolf packs, id really like to run a server of this pack for my friends and myself but this problem just keeps on persisting

**Comment by Dragonic-magic** [comment]
also in the ftb server download the pack doesnt have a eula just so you know, have to add one yourself. oh my now the topics important^^" thank you^-^

**Comment by Dragonic-magic** [comment]
thanks for the update DD, its all good now and for others you no longer have to remove any mods the 1.3 server runs on its own from the batch file itll crash once this is just due to the eula not being accept/created yet yust change false to true then relaunch and it works, thank you again DD
